spring.application.name=ciats-lite

spring.data.mongodb.uri=mongodb://localhost:27017/ciats_db

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs

logging.level.com.jabejo.ciats_lite=DEBUG
logging.file.name=logs/ciats-lite.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n